apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eli-test3
  region: us-east-1
  version: "1.21"
managedNodeGroups:
  - name: default-ng
    instanceType: t3a.large
    iam:
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::126800174746:policy/sts_all
    ssh:
      allow: true
      publicKeyName: cnvrg-east1
    minSize: 1
    desiredCapacity: 1
    maxSize: 4
    availabilityZones: ['us-east-1a']
  - name: dl1-ng-2
    instanceType: dl1.24xlarge
    volumeSize: 200
    instancePrefix: dl1-ng-1d-worker
    ami: ami-02aeb7b9bc3ad7f37
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        fsx: true
        cloudWatch: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::126800174746:policy/sts_all
    ssh:
      allow: true
      publicKeyName: cnvrg-east1
    minSize: 1
    desiredCapacity: 1
    maxSize: 4
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh eli-test3
    availabilityZones: ['us-east-1a']

availabilityZones: ['us-east-1a','us-east-1b']
